### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/courtformsonline.org#50]
- [ ] Edit github publish location
- [ ] Confirm DNS
- [ ] Test publishing

**Comment by samglover** [comment]
- [ ] Update (to `''`) or remove the `basePath` variable definition from [next.config.js](https://github.com/SuffolkLITLab/courtformsonline.org/blob/main/next.config.js)
  The `isProd` constant and the commented-out definitions of `basePath` and `assetPath` won't be doing anything important at that point and can also be removed.
- [ ] \[optional] Remove the **basePath** variable from the following components by (1) deleting the `import nextConfig from '../../../next.config';` line, and (2) removing the `nextConfig.basePath` variable from the `src` property of **\<Image>** component(s).
  - [ ] AffiliatesSection
  - [ ] Footer
  - [ ] NavigationBar
  - [ ] ThankYou
